"""Bounded saved-data diagnosis and one iteration-controlled startup solve."""
import os
for name in ('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS','MKL_NUM_THREADS'):
    os.environ[name]='1'
import sys, json, gzip, hashlib, time
from pathlib import Path
from copy import deepcopy
from unittest.mock import patch
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT))
import numpy as np
from tools.state_io import atomic_json
OUT=Path(__file__).resolve().parent
read=lambda p:json.loads(p.read_text(encoding='utf8'))

def archive(stage,sub):
    root=ROOT/'runs'/stage/sub
    inp=read(root/'input.json');summary=read(root/'summary.json')
    backend=root/'sessions'/inp['run_id']/'executions'/summary['execution_id']/'backend'
    return inp,summary,backend,read(backend/'controller_observations.json')

def freeze():
    assert not (OUT/'saved_diagnosis.json').exists()
    old,osum,ob,oo=archive('stage326_gvs_kernel_efficiency_20260928','confirmation')
    inp,s,b,o=archive('stage327_multisegment_tracking_20260928','deterministic')
    plan=read(b/'control_spec.json')
    from schemas.platform import SessionInput
    from extensions.tendon_family.gvs_profile import candidate_numerical,load_profile
    from extensions.tendon_family.tracking import checked_tracking,reference_at
    parsed=SessionInput.model_validate(inp)
    numerical=candidate_numerical(parsed,checked_tracking(parsed),load_profile())
    samples=[];facts=[]
    for i in (0,4):
        row=o[i];previous=o[i-1]['actual_tension_n'] if i else plan['reference']['u0']
        warm=numerical['warm_guess'] if i==0 else dict(states=[row['measured_initial_state']]*11,tensions=[previous]*10)
        samples.append(dict(time_s=row['time_s'],measured_x=row['measured_initial_state'],previous_u=previous,warm=warm,
            warm_provenance='exact public candidate numerical preparation' if i==0 else 'reconstructed constant previous tensions and repeated measured state; historical warm plan unavailable',
            geometry=dict(tip=row['tip_position_m'],gvs_projection=dict(projection_residual_max_rad_m=row['gvs_projection_residual_max_rad_m']))))
        facts.append(dict(time_s=row['time_s'],observation=row,previous_u=previous,
            first_command_change_from_actual_previous_n=float(np.max(abs(np.array(row['actual_tension_n'])-previous))),
            historical_warm_provenance='public initial_state_pretension, regenerated by implicit integration' if i==0 else 'previous accepted plan shifted one interval and regenerated; full warm plan not retained',
            full_horizon_available=False,raw_objective=None,
            missing='Full historical plans and raw objective not exported by backend. Stage326 modified t=0 plan is separately retained.'))
    m=read(ROOT/'runs/stage326_gvs_kernel_efficiency_20260928/modified.json')['records'][0]
    checks={k:old[k]==inp[k] for k in ('robot','policy')}
    checks['initializer']=old['task']['initializer']==inp['task']['initializer']
    checks['environment']=old['task']['environment']==inp['task']['environment']
    checks['initial_measurement']=oo[0]['measured_initial_state']==o[0]['measured_initial_state']
    checks['startup_reference_nodes']=oo[0]['prediction_timing']==o[0]['prediction_timing']
    checks['modified_first_command']=m['selected_tensions'][0]==o[0]['actual_tension_n']
    checks['modified_first_prediction']=m['selected_states'][1]==o[0]['one_step_prediction']['state']
    checks['modified_recovered_objective']=m['objective']==o[0]['feedback']['delivered_objective']
    assert all(checks.values()),checks
    trajectory=json.loads(gzip.decompress((b/'trajectory.json.gz').read_bytes()))
    endpoints=[]
    for i in (4,5,59):
        row=trajectory[i];pred=o[i]['one_step_prediction'];ref,_=reference_at(inp['task']['goal']['data'],row['time_s'])
        assert abs(pred['time_s']-row['time_s'])<1e-12 and pred['applied_tension_n']==row['tension_n']
        endpoints.append(dict(time_s=row['time_s'],actual_error_m=float(np.linalg.norm(np.array(row['tip_m'])-ref)),predicted_error_m=float(np.linalg.norm(np.array(pred['tip_position_m'])-ref)),discrepancy_m=float(np.linalg.norm(np.array(pred['tip_position_m'])-row['tip_m']))))
    atomic_json(OUT/'selected_states.json',dict(input=inp,plan=plan,physics=read(b/'resolved_physics.json'),samples=samples,observation_source=b.relative_to(ROOT).as_posix()+'/controller_observations.json',numerical_provenance=numerical['provenance']))
    atomic_json(OUT/'saved_diagnosis.json',dict(checks=checks,operating_points=facts,aligned_endpoints=endpoints,
        stage327_facts=s['factual_result'],stage327_segments=s['tracking']['segment_diagnostics'],
        stage326_first=oo[0],stage326_modified_raw_objective=m['diagnostics']['returned_iterate_objective'],
        maximum_first_command_difference_n=float(np.max(abs(np.array(oo[0]['actual_tension_n'])-o[0]['actual_tension_n']))),
        sources=[str(p.relative_to(ROOT)).replace('\\','/') for p in (ob/'controller_observations.json',b/'controller_observations.json',b/'trajectory.json.gz')]))
    print(json.dumps(dict(checks=checks,endpoints=endpoints),indent=2))

def metrics(ws,values,previous):
    X=np.array([[values[f'x/{k}/{j}']*ws.state_scales[j] for j in range(2*ws.n)] for k in range(11)])
    tips=np.array([np.asarray(ws._motion(x[:ws.n],x[ws.n:])[0]).ravel() for x in X])
    errors=np.linalg.norm(tips-ws.reference_positions,axis=1)
    return dict(peak_m=float(max(errors[1:])),terminal_m=float(errors[-1]),errors_m=errors.tolist(),
        first_command_change_n=float(max(abs(values[f'u/0/{t}']-p) for t,p in zip(ws.tendons,previous))))

def diagnostic():
    assert not (OUT/'diagnostic_started.json').exists()
    atomic_json(OUT/'diagnostic_started.json',dict(nlp_attempts=1,cap=20,retained_callback_indices=[15,16,17],production_benchmark=False))
    from schemas.platform import SessionInput
    from extensions.tendon_family.gvs_trajectory import TrajectoryWorkspace
    from extensions.optimization.ipopt import _FeasibleIterate
    saved=read(OUT/'selected_states.json');inp=SessionInput.model_validate(saved['input']);s=saved['samples'][0]
    p=deepcopy(saved['plan']['effective_parameters']);p.update(max_iterations=20,feasible_return=None,recover_returned_tensions=False)
    ws=TrajectoryWorkspace(inp.task,inp.robot,p,s['measured_x'],s['previous_u'])
    ws.solver.diagnostic_trace=True
    retained=[];original=_FeasibleIterate.eval
    def capture(cb,args):
        result=original(cb,args)
        if cb.iteration in (15,16,17):
            items=dict(zip(cb.names,args));retained.append(dict(callback_index=cb.iteration,raw_values=np.asarray(items['x']).ravel().tolist(),raw_objective=float(items['f'])))
        return result
    started=time.perf_counter()
    with patch.object(_FeasibleIterate,'eval',capture):
        solved=ws.solve(s['measured_x'],s['previous_u'],warm=s['warm'],elapsed_s=0.)
    elapsed=time.perf_counter()-started
    atomic_json(OUT/'diagnostic_raw.json',dict(solved=solved,retained=retained,complete_s=elapsed))
    records=[];order=ws.problem.objective_function.data['variable_order']
    for candidate in retained:
        raw=dict(zip(order,candidate['raw_values']));values=dict(raw);state=np.array(s['measured_x']);start=time.perf_counter()
        for k in range(1,11):
            u=np.array([raw[f'u/{k-1}/{t}'] for t in ws.tendons]);guess=np.array([raw[f'x/{k}/{j}'] for j in range(2*ws.n)])*ws.state_scales
            state,_=ws._extend_tail(state,u,guess)
            for j,v in enumerate(state):values[f'x/{k}/{j}']=float(v/ws.state_scales[j])
        recovery_s=time.perf_counter()-start
        check=ws.solver.evaluate_candidate(ws.problem,values)
        record=dict(**candidate,recovered_values=values,recovery_s=recovery_s,check=check,metrics=metrics(ws,values,s['previous_u']))
        records.append(record)
        atomic_json(OUT/'diagnostic_recovered.json',dict(records=records,nlp_solves=1,recovery_integrations=len(records)*10))
        print(json.dumps({k:v for k,v in record.items() if k not in ('raw_values','recovered_values')},indent=2),flush=True)
    print('callback final',solved['diagnostics']['iteration_trace'][-1]['iteration'],'reported',solved['result']['iterations'],flush=True)

if __name__=='__main__':
    {'freeze':freeze,'diagnostic':diagnostic}[sys.argv[1]]()
