function row=tf_observe(p,g,y,u,target,t,dt,before)
n=numel(p.dofs); nb=numel(p.parts); positions=zeros(nb,3); rotations=zeros(nb,3,3);
for i=1:nb, positions(i,:)=g.bodies(i).p'; rotations(i,:,:)=g.bodies(i).R; end
row=struct('time_s',t+dt,'solver_time_s',t,'tip_m',g.tip',...
    'qpos_rad',y(1:n)','qvel_rad_s',y(n+1:end)','actuator_command',u',...
    'command_m',target','tendon_length_m',g.lengths',...
    'solver_tendon_length_m',before.geometry.lengths','tension_n',before.tension',...
    'solver_qfrc_actuator_nm',before.drive','solver_qfrc_passive_nm',(before.spring+before.damping)',...
    'external_torque_nm',before.external','contact_normal_approx_n',before.normal',...
    'body_positions_m',positions,'body_rotations',rotations,'tendon_routes_m',{g.routes});
end
