"""Human-owned top-level categories; legacy ToolResult codes remain intact."""
from enum import Enum


class FailureCategory(str, Enum):
    DESIGN_INFEASIBLE = "DESIGN_INFEASIBLE"
    COLLISION_INFEASIBLE = "COLLISION_INFEASIBLE"
    ACTUATION_INSUFFICIENT = "ACTUATION_INSUFFICIENT"
    MODEL_MISMATCH = "MODEL_MISMATCH"
    CONTROL_FAILURE = "CONTROL_FAILURE"
    ACTUATOR_LIMIT = "ACTUATOR_LIMIT"
    SIMULATION_ERROR = "SIMULATION_ERROR"
    NUMERICAL_FAILURE = "NUMERICAL_FAILURE"
    CAPABILITY_MISSING = "CAPABILITY_MISSING"
    PHYSICS_ASSUMPTION_REQUIRED = "PHYSICS_ASSUMPTION_REQUIRED"
    TASK_FAILED = "TASK_FAILED"
    UNKNOWN = "UNKNOWN"


LEGACY_MAP = {
    "UNSUPPORTED_ROBOT_FAMILY": "CAPABILITY_MISSING",
    "UNSUPPORTED_DESIGN_CONFIGURATION": "CAPABILITY_MISSING",
    "IMPLEMENTATION_REQUIRED": "CAPABILITY_MISSING",
    "OUT_OF_GRAMMAR": "CAPABILITY_MISSING",
    "PHYSICS_ERROR": "SIMULATION_ERROR",
    "NONFINITE_STATE": "NUMERICAL_FAILURE",
    "PCC_INVALID_COMMAND": "CONTROL_FAILURE",
    "INVALID_TENDON_COMMAND": "CONTROL_FAILURE",
    "INVALID_DESIGN": "DESIGN_INFEASIBLE",
    "INVALID_ENVIRONMENT": "UNKNOWN",
    "INVALID_SPEC": "UNKNOWN",
}


def failure_category(code: str | None) -> str | None:
    if code is None:
        return None
    mapped = LEGACY_MAP.get(code, code)
    return mapped if mapped in FailureCategory._value2member_map_ else "UNKNOWN"
