"""Developer protocols; concrete serialized state still uses registry contracts."""
from typing import Protocol
from schemas.platform import Payload, BackendResult, EvaluationResult, SessionInput, TaskDefinition, EvidenceRef


class ModelAdapter(Protocol):
    """1.0 text transport. Registry declares real_requests, timeout and cancellation."""
    adapter_id: str
    def encode(self, model_input, config) -> dict: ...
    def respond(self, serialized_request: dict, turn: int): ...
    def decode(self, response, turn: int, tool_bindings: dict): ...


class AgentStrategy(Protocol):
    """1.0 typed action selection; no execution or accounting authority."""
    def decide(self, decoded, context): ...


class CandidateBuilder(Protocol):
    """1.0 receives a private copy; may modify declared design/discretization data only."""
    def __call__(self, baseline: SessionInput, parameters, changes: dict[str, object]) -> SessionInput: ...


class Worker(Protocol):
    """WorkerOutput 2.0; own child session, common restricted execution client."""
    def __call__(self, order, parameters, fixed_input, client): ...


class WorkerResultChecker(Protocol):
    def __call__(self, order, output, source, registry, evidence: list): ...


class OneShotBackend(Protocol):
    @staticmethod
    def check(inp: SessionInput, parameters, control) -> None: ...
    def compile(self, inp: SessionInput, registry) -> None: ...
    def initialize(self, initial: Payload, controller) -> None: ...
    def run(self, **declared_options) -> BackendResult: ...
    def close(self) -> None: ...


class SteppingBackend(OneShotBackend, Protocol):
    def step(self) -> None: ...
    def observe(self) -> list: ...
    def export(self) -> BackendResult: ...
    def cancel(self) -> None: ...


class Controller(Protocol):
    def reset(self) -> None: ...
    def restore(self, state) -> None: ...
    def command(self, time_s: float, observations): ...
    def finish(self, interrupted: bool = False) -> None: ...
    def checkpoint(self) -> Payload: ...


class Search(Protocol):
    def propose(self) -> dict[str, float]: ...
    def feedback(self, score: float | None) -> None: ...
    def stopped(self) -> bool: ...
    def save(self) -> Payload: ...
    def restore(self, state) -> None: ...


class Evaluator(Protocol):
    def __call__(self, task: TaskDefinition, result: BackendResult, source: EvidenceRef, registry,
                 comparison_identity: str) -> EvaluationResult: ...
