"""Developer protocols; concrete serialized state still uses registry contracts."""
from typing import Protocol
from schemas.platform import Payload, BackendResult, EvaluationResult, SessionInput, TaskDefinition, EvidenceRef


class OneShotBackend(Protocol):
    @staticmethod
    def check(inp: SessionInput, parameters, control) -> None: ...
    def compile(self, inp: SessionInput, registry) -> None: ...
    def initialize(self, initial: Payload, controller) -> None: ...
    def run(self, **declared_options) -> BackendResult: ...
    def close(self) -> None: ...


class SteppingBackend(OneShotBackend, Protocol):
    def step(self) -> None: ...
    def observe(self) -> list: ...
    def export(self) -> BackendResult: ...
    def cancel(self) -> None: ...


class Controller(Protocol):
    def reset(self) -> None: ...
    def restore(self, state) -> None: ...
    def command(self, time_s: float, observations): ...
    def finish(self, interrupted: bool = False) -> None: ...
    def checkpoint(self) -> Payload: ...


class Search(Protocol):
    def propose(self) -> dict[str, float]: ...
    def feedback(self, score: float | None) -> None: ...
    def stopped(self) -> bool: ...
    def save(self) -> Payload: ...
    def restore(self, state) -> None: ...


class Evaluator(Protocol):
    def __call__(self, task: TaskDefinition, result: BackendResult, source: EvidenceRef, registry,
                 comparison_identity: str) -> EvaluationResult: ...
