"""Machine-readable engineering strategies. No field grants execution authority."""
from enum import Enum
from typing import Literal
from pydantic import AwareDatetime, Field, model_validator
from schemas.common import Contract
from schemas.evidence import ArtifactReference, Identifier
from schemas.failure_taxonomy import FailureCategory
from schemas.trace import Actor


class SkillStatus(str, Enum):
    CANDIDATE = "candidate"
    VALIDATED = "validated"
    APPROVED = "approved"
    DEPRECATED = "deprecated"
    REJECTED = "rejected"


class SkillCategory(str, Enum):
    DESIGN = "DESIGN"
    MODEL_SELECTION = "MODEL_SELECTION"
    CONTROL = "CONTROL"
    DIAGNOSIS = "DIAGNOSIS"
    CODING_SIMULATION = "CODING_SIMULATION"


class Applicability(Contract):
    robot_families: tuple[Identifier, ...] = Field(min_length=1)
    task_types: tuple[Identifier, ...] = Field(min_length=1)
    model_levels: tuple[Literal["M0", "M1", "M2", "M3"], ...] = Field(min_length=1)
    control_levels: tuple[Literal["C0", "C1", "C2", "C3"], ...] = Field(min_length=1)


class MetricPredicate(Contract):
    tool: Identifier
    metric: Identifier
    operator: Literal["eq", "gt", "ge", "lt", "le"]
    value: float | bool
    evidence: ArtifactReference


class TriggerSignature(Contract):
    failure_categories: tuple[FailureCategory, ...] = ()
    metrics: tuple[MetricPredicate, ...] = ()


class StrategyStep(Contract):
    action: Literal["invoke_tool", "inspect_evidence", "request_human_review"]
    tool: Identifier | None = None
    evidence_refs: tuple[ArtifactReference, ...] = ()
    instruction: str = Field(min_length=1, max_length=1000)
    # No shell, arbitrary code, mutation path, task gate assignment or execution result.

    @model_validator(mode="after")
    def action_contract(self):
        if (self.action == "invoke_tool") != (self.tool is not None):
            raise ValueError("Only invoke_tool steps require a tool")
        if self.action == "inspect_evidence" and not self.evidence_refs:
            raise ValueError("Inspection requires evidence")
        return self


class SkillValidationRecord(Contract):
    validation_id: Identifier
    skill_ref: str = Field(pattern=r"^[A-Za-z0-9_.-]+@[1-9][0-9]*$")
    strategy_sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    method: Literal["deterministic", "cross_run", "human_review"]
    outcome: Literal["passed", "failed", "contradicted"]
    validated_runs: tuple[Identifier, ...] = ()
    failed_validation_runs: tuple[Identifier, ...] = ()
    task_coverage: tuple[Identifier, ...] = ()
    robot_coverage: tuple[Identifier, ...] = ()
    seed_coverage: tuple[int, ...] = ()
    evidence_refs: tuple[ArtifactReference, ...] = Field(min_length=1)
    validated_by: Actor
    validated_at: AwareDatetime
    summary: str = Field(min_length=1, max_length=1000)

    @model_validator(mode="after")
    def run_outcomes(self):
        if not (self.validated_runs or self.failed_validation_runs):
            raise ValueError("Validation requires run evidence")
        if set(self.validated_runs) & set(self.failed_validation_runs):
            raise ValueError("Run cannot both pass and fail the same validation")
        if self.outcome == "passed" and (not self.validated_runs or self.failed_validation_runs):
            raise ValueError("Passed validation requires success and no failed runs")
        if self.outcome != "passed" and not self.failed_validation_runs:
            raise ValueError("Negative validation must retain failed runs")
        return self


class SkillValidationEvidence(Contract):
    """Result supplied by a deterministic experiment or Human review, never generated by admission."""
    skill_ref: str = Field(pattern=r"^[A-Za-z0-9_.-]+@[1-9][0-9]*$")
    strategy_sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    run_id: Identifier
    worked: bool = Field(strict=True)
    summary: str = Field(min_length=1, max_length=1000)


class SkillProvenance(Contract):
    source_runs: tuple[Identifier, ...] = Field(min_length=1)
    source_findings: tuple[ArtifactReference, ...] = ()
    supporting_evidence: tuple[ArtifactReference, ...] = Field(min_length=1)
    created_by: Actor
    created_at: AwareDatetime
    last_validated_at: AwareDatetime | None = None


class HumanApproval(Contract):
    actor: Literal["human"]
    approved_by: str = Field(min_length=1, max_length=160)
    approved_at: AwareDatetime
    content_sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    rationale: str = Field(min_length=1, max_length=1000)


class Skill(Contract):
    skill_id: Identifier
    name: str = Field(min_length=1, max_length=256)
    version: int = Field(ge=1, strict=True)
    status: SkillStatus
    category: SkillCategory
    description: str = Field(min_length=1, max_length=2000)
    trigger_signature: TriggerSignature
    when_to_apply: tuple[str, ...] = Field(min_length=1)
    when_not_to_apply: tuple[str, ...] = Field(min_length=1)
    applicability: Applicability
    required_tools: tuple[Identifier, ...] = Field(min_length=1)
    strategy: tuple[StrategyStep, ...] = Field(min_length=1)
    negative_constraints: tuple[str, ...] = Field(min_length=1)
    evidence: tuple[ArtifactReference, ...] = Field(min_length=1)
    validation: tuple[SkillValidationRecord, ...] = ()
    provenance: SkillProvenance
    human_approval: HumanApproval | None = None
    requires_new_physics: bool = False
    causal_claim: Literal["none"] = "none"
    authority: Literal["recommendation_only"] = "recommendation_only"
    supersedes: str | None = Field(default=None, pattern=r"^[A-Za-z0-9_.-]+@[1-9][0-9]*$")
    deprecated_by: str | None = Field(default=None, pattern=r"^[A-Za-z0-9_.-]+@[1-9][0-9]*$")

    @property
    def reference(self):
        return f"{self.skill_id}@{self.version}"
